import { getCloudflareContext } from "@opennextjs/cloudflare";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "./components/site-header";
import { AppProviders } from "./providers";
import ThemeToggle from "./components/theme-toggle";

const APP_LOCALE_HEADER = "x-app-locale";
const REQUEST_PATHNAME_HEADER = "x-paragify-pathname";
const DEFAULT_HTML_LANG = "en";

type DbBindings = CloudflareEnv & { DB?: D1Database };

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

function normalizeHtmlLangTag(value: string | null | undefined): string {
	const normalized = value?.trim().replace(/_/g, "-") ?? "";
	if (!normalized) {
		return DEFAULT_HTML_LANG;
	}

	const segments = normalized
		.split("-")
		.map((segment) => segment.trim())
		.filter(Boolean);
	if (segments.length === 0) {
		return DEFAULT_HTML_LANG;
	}

	return segments
		.map((segment, index) => {
			if (index === 0) {
				return segment.toLowerCase();
			}
			if (/^[A-Za-z]{4}$/.test(segment)) {
				return `${segment.charAt(0).toUpperCase()}${segment.slice(1).toLowerCase()}`;
			}
			if (/^[A-Za-z]{2}$/.test(segment) || /^\d{3}$/.test(segment)) {
				return segment.toUpperCase();
			}
			return segment.toLowerCase();
		})
		.join("-");
}

function extractPostSlugFromPathname(pathname: string | null): string | null {
	const normalizedPath = pathname?.trim() ?? "";
	if (!normalizedPath.startsWith("/p/")) {
		return null;
	}

	const pathSegment = normalizedPath.slice(3).split("/")[0]?.trim() ?? "";
	if (!pathSegment) {
		return null;
	}

	try {
		return decodeURIComponent(pathSegment);
	} catch {
		return pathSegment;
	}
}

function normalizeAppLocaleToHtmlLang(value: string | null | undefined): string {
	const normalized = value?.trim().toLowerCase() ?? "";
	if (normalized === "zh") {
		return "zh-HK";
	}
	if (normalized === "ja") {
		return "ja-JP";
	}
	if (normalized === "en") {
		return "en";
	}
	return normalizeHtmlLangTag(value);
}

async function resolveHtmlLang(): Promise<string> {
	const requestHeaders = await headers();
	const postSlug = extractPostSlugFromPathname(requestHeaders.get(REQUEST_PATHNAME_HEADER));
	if (!postSlug) {
		return normalizeAppLocaleToHtmlLang(requestHeaders.get(APP_LOCALE_HEADER));
	}

	try {
		const { env } = await getCloudflareContext({ async: true });
		const db = (env as DbBindings | undefined)?.DB;
		if (!db) {
			return DEFAULT_HTML_LANG;
		}

		const maybePostId = /^\d+$/.test(postSlug) ? Number(postSlug) : null;
		const whereClause = maybePostId ? "(post_slug = ? OR post_id = ?)" : "(post_slug = ?)";
		const bindings = maybePostId ? [postSlug, maybePostId] : [postSlug];
		const row = await db
			.prepare(`SELECT locale FROM posts WHERE visibility = 'public' AND ${whereClause} LIMIT 1`)
			.bind(...bindings)
			.first<{ locale: string | null }>();

		return normalizeHtmlLangTag(row?.locale);
	} catch (error) {
		console.error("Failed to resolve html lang.", error);
		return DEFAULT_HTML_LANG;
	}
}

function readInitialAppLocale(value: string | null | undefined): "en" | "zh" | "ja" {
	const normalized = value?.trim().toLowerCase() ?? "";
	if (normalized === "zh" || normalized === "ja") {
		return normalized;
	}
	return "en";
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const requestHeaders = await headers();
	const htmlLang = await resolveHtmlLang();
	const initialLocale = readInitialAppLocale(requestHeaders.get(APP_LOCALE_HEADER));

	return (
		<html lang={htmlLang}>
			<head>
				<link rel="icon" href="/favicon.svg" type="image/svg+xml"></link>
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<AppProviders initialLocale={initialLocale}>
					<SiteHeader />
					{children}
					<ThemeToggle />
				</AppProviders>
			</body>
		</html>
	);
}
